language: node_js
node_js:
  - "4.1"
  - "4.0"
install:
 - npm install -g mocha-phantomjs
 - npm install
 - npm -g install npm@latest

notifications:
  email:
    recipients:
      - simon.1994@hotmail.de
    on_success: change
    on_failure: always