language: node_js
node_js:
  - "4.1"
  - "4.0"
before_install:
  - npm install -g mocha
  - npm -g install npm@latest
  - echo "Installed mocha"
notifications:
  email:
    recipients:
      - simon.1994@hotmail.de
    on_success: change
    on_failure: always